config:
  moduleDescription: "Domain module. Contains a parser for logical responses. The module consists of the following components: 1. Text strings for 'true' and 'false' responses."
  excludeTranslated: true
