config:
  moduleDescription: "Course screen. This screen displays course theory on a specific topic in MD5 format. The screen consists of the following components: 1. A basic toolbar. 2. Content in MD5 format. 3. A 'Start Testing' button."
  excludeTranslated: true
