config:
  moduleDescription: "Task screen 'Choose the correct answers.' The user selects the correct answers using checkboxes, and the screen transitions to the next question after selecting a certain number of answers. The screen consists of the following components: 1. Question. 2. List of answers to choose from."
  excludeTranslated: true
