config:
  moduleDescription: "Content screen. Allows you to select a question database or upload a new one from a file. The screen consists of the following components: 1. A basic toolbar. 2. A banner to add a new file. 3. A list of already uploaded databases, from which you can select the desired one."
  excludeTranslated: true
